vehiculos/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import permission_required
from vehiculos.views import *

urlpatterns = [
	url(r'^SOAT/$', 'vehiculos.views.soat', name = 'soat'),
	url(r'^historial/$', 'vehiculos.views.historialVehiculo', name = 'historial'),
	url(r'^historial-vehiculo/(?P<pk>[\w\-]+)/$', vehiculoDetail.as_view(), name = 'detail_vehiculo'),
	url(r'^vehiculo/nuevo/$', createVehiculoView.as_view(), name = 'create_vehiculo'),
	url(r'^vehiculo/actualizar/(?P<pk>[\w\-]+)/$', updateVehiculoView.as_view(), name = 'update_vehiculo'),
	url(r'^vehiculo/$', listVehiculosView.as_view(), name = 'list_vehiculo'),
	url(r'^obtener-linea/(?P<marca>[\w\-]+)/$', 'vehiculos.views.getLinea', name = 'get_linea'),

	#Reportes
	url(r'^vehiculo-soat/$', 'vehiculos.views.vehiculo_soat', name = 'vehiculo_soat'),
	url(r'^vehivulo-reporte-soat/(?P<fecha_in>[\w\-]+)/(?P<fecha_fin>[\w\-]+)/$', ReporteSoatPDFView.as_view(), name = 'vehiculo_reporte_soat'),
]

vehiculos/models.py
# -*- encoding: utf-8 -*-
from django.db import models

from clientes.models import clienteModel


class MarcaModel(models.Model):
	marca = models.CharField(max_length=50)

	def __str__(self):
		return u'%s' % (self.marca)

	def __unicode__(self):
		return u'%s' % (self.marca)


class tipoVehiculoModel(models.Model):
	nombre = models.CharField(max_length=50)

	def __str__(self):
		return u'%s' % (self.nombre)

	def __unicode__(self):
		return u'%s' % (self.nombre)

class tipoLineaModel(models.Model):
	nombre_tipo = models.CharField(max_length = 50)
	marca = models.ForeignKey(MarcaModel, null=True, blank=True)

	def __str__(self):
		return u'%s' % (self.nombre_tipo)

	def __unicode__(self):
		return u'%s' % (self.nombre_tipo)

class vehiculoModel(models.Model):
	placa = models.CharField(max_length=10, null=False, blank=False)
	cilindraje = models.IntegerField(null=True, blank=True)
	#clase = models.CharField(max_length=50, null=True, blank=True)
	linea = models.ForeignKey(tipoLineaModel, null=True, blank=True)
	kilometraje_actual = models.CharField(max_length = 10, null = True, blank = True)
	soat = models.DateField(auto_now = False, null = True, blank = True)
	#tipo = models.ForeignKey(tipoVehiculoModel, null=True, blank=True)
	categoria = models.ForeignKey(tipoVehiculoModel, null=True, blank=True)
	modelo = models.IntegerField(null=True, blank=True)
	cliente = models.ForeignKey(clienteModel, null=False, blank=False)
	foto = models.ImageField(upload_to = 'img/vehiculo/', default = 'img/none.jpg', null=True, blank=True)
	foto_chasis = models.ImageField(upload_to = 'img/vehiculo/', default = 'img/none.jpg', null=True, blank=True)
	foto_motor = models.ImageField(upload_to = 'img/vehiculo/', default = 'img/none.jpg', null=True, blank=True)
	n_chasis = models.CharField(max_length = 50, blank=True, null=True)
	n_motor = models.CharField(max_length = 50, blank=True, null=True)

	def __str__(self):
		return self.placa

	def __unicode__(self):
		return self.placa

vehiculos/templates/create_vehiculo.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head %}
	<link href="{% static 'css/chosen.css' %}" rel="stylesheet">
	<script src="{% static 'js/chosen.js' %}"></script>
{% endblock head %}

{% block contentViewTitle %}
	<h3>Crear nuevo vehiculo</h3>
{% endblock contentViewTitle %}
{% block content %}
	{% if form.errors %}
		<div class="alert alert-danger">
			Corrija los <strong>errores</strong> por favor
		</div>
	{% endif %}
	<div class="well">
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<div class="row">
				<div class="form-group col-md-6">
					<label>{{ form.placa.label }}</label>
					{{ form.placa }}
					{{ form.placa.errors }}
				</div>
				<div class="form-group col-md-6">
					<label>{{ form.kilometraje_actual.label }}</label>
					{{ form.kilometraje_actual }}
					{{ form.kilometraje_actual.errors }}
				</div>
				<div class="form-group col-md-6">
					<label>{{ form.marca.label }}</label>
					{{ form.marca }}
					{{ form.marca.errors }}
				</div>
				<div class="form-group col-md-6">
					<label>{{ form.linea.label }}</label>
					{{ form.linea }}
					{{ form.linea.errors }}
				</div>
				<div class="form-group col-md-6">
					<label>{{ form.soat.label }}</label>
					{{ form.soat }}
					{{ form.soat.errors }}
				</div>
				<div class="form-group col-md-6">
					<label>{{ form.cilindraje.label }}</label>
					{{ form.cilindraje }}
					{{ form.cilindraje.errors }}
				</div>
				<div class="form-group col-md-6">
					<label>{{ form.modelo.label }}</label>
					{{ form.modelo }}
					{{ form.modelo.errors }}
				</div>
				<div class="form-group col-md-6">
					<label>{{ form.categoria.label }}</label>
					{{ form.categoria }}
					{{ form.categoria.errors }}
				</div>
				<div class="form-group col-md-6">
					<label>N° Chasis</label>
					{{ form.n_chasis }}
					{{ form.n_chasis.errors }}
				</div>
				<div class="form-group col-md-6">
					<label>N° Motor</label>
					{{ form.n_motor }}
					{{ form.n_motor.errors }}
				</div>
				<div class="form-group col-md-6">
					<label>{{ form.cliente.label }}</label>
					{{ form.cliente }}
					{{ form.cliente.errors }}
				</div>
				<div class="col-md-12">
					<div class="form-group col-md-6">
						<label>{{ form.foto.label }}</label>
						{{ form.foto }}
						{{ form.foto.errors }}
					</div>
					<div class="form-group col-md-6">
						<label>{{ form.foto_chasis.label }}</label>
						{{ form.foto_chasis }}
						{{ form.foto_chasis.errors }}
					</div>
					<div class="form-group col-md-6">
						<label>{{ form.foto_motor.label }}</label>
						{{ form.foto_motor }}
						{{ form.foto_motor.errors }}
					</div>
				</div>
			</div>
			<div class="form-group text-center">
				<input type="submit" value="Guardar" class="btn btn-success">
				<a href="{% url 'create_clientes' %}" class="btn btn-primary">Crear cliente</a>
			</div>
		</form>
	</div>
{% endblock content %}

{% block scripts %}
	<script>
		$(".chosen").chosen();
		$( "form" ).submit(function( event ) {
			if($('#id_linea').val() == ''){
				$("#id_marca").val('').trigger('change');
			}
		});
		$(document).ready(
			function(){
				$("select#id_marca").change(function() {
					console.log(0)
					if ($(this).val() == '') {
						$("select#id_linea").html("<option value=''>--------</option>");
						$("select#id_linea").attr('disabled', true);
						$("select#id_linea").removeAttr('class', 'chosen');
						$("select#id_linea").attr('class', 'form-control');
					}else{
						var url = "/obtener-linea/"+$(this).val()+"/";
						var brand = $(this).val();
						$.getJSON(url, function(models) {
							var options = '<option value="">--------</option>';
							for (var i = 0; i < models.length; i++) {
								options += '<option value="' + models[i].pk + '">' + models[i].fields['nombre_tipo'] + '</option>';
							}
							$("select#id_linea").html(options);
							$("select#id_linea").attr('class', 'form-control chosen');
							$("select#id_linea option:first").attr('selected', 'selected');
							$("select#id_linea").attr('disabled', false);
						});
					}
				});
			}
		);
	</script>
{% endblock scripts %}

vehiculos/templates/detail_vehiculo.html
{% extends "base.html" %}

{% load staticfiles %}

{% block contentViewTitle %}
	<div class="col-4">
		<h3>Historial del vehiculo</h3>
	</div>
	<div class="col-8">
		<a href="{% url 'historial' %}" class="btn btn-info">Consultar otro</a>
	</div>
{% endblock contentViewTitle %}
{% block content %}
	<div class="row">
		<div class="well col-8">
			<h3>Datos del Vehiculo</h3>
			<div class="row">
				<div class="col-8">
					<figure>
						<img src="{% static vehiculo.foto %}" width="400px">
					</figure>
				</div>
				<div class="col-4">
					<br>
					<p><strong>Placa: </strong>{{ vehiculo.placa }}</p>
					<p><strong>Marca: </strong>{{ vehiculo.linea.marca }}</p>
					<p><strong>Modelo:</strong> {{ vehiculo.modelo }}</p>
					<p><strong>Cilindraje:</strong> {{ vehiculo.cilindraje }}</p>
					<p><strong>Categoria:</strong> {{ vehiculo.categoria }}</p>
					<p><strong>SOAT:</strong> {{ vehiculo.soat }}</p>
					<p><strong>N° Chasis:</strong> {{ vehiculo.n_chasis }}</p>
					<p><strong>N° Motor:</strong> {{ vehiculo.n_motor }}</p>
				</div>
			</div>
		</div>
		<div class="well col-4">
			<h3>Cliente</h3>
			<p><strong>Nombre: </strong>{{ vehiculo.cliente }} </p>
			<p><strong>Doc. Identidad: </strong>{{ vehiculo.cliente.documento}}</p>
			<p><strong>Telefono: </strong>{{ vehiculo.cliente.telefono }} - {{ vehiculo.cliente.celular }}</p>
			<p><strong>Email: </strong>{{ vehiculo.cliente.email }}</p>
			<p><strong>Dirección: </strong>{{ vehiculo.cliente.direccion }}</p>
			<p><strong>Fecha nacimiento: </strong>{{ vehiculo.cliente.fnaci }}</p>
		</div>
	</div>
	<h3>Ordenes de servicios</h3>
	{% if ordenes_servicios %}
		<table class="table table-striped table-hover ">
			<thead>
				<tr>
					<th>Código Orden</th>
					<th>Fecha</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				{% for orden in ordenes_servicios %}
						<tr>
							<td>{{ orden.id }}</td>
							<td>{{ orden.fecha }}</td>
							<td>
								<a href="{% url 'detalle_orden_servicio' orden.pk %}" target="_blank">
									Ver
								</a>
							</td>
						</tr>
					</a>
				{% endfor %}
			</tbody>
		</table>
	{% else %}
	<div class="alert alert-info" role="alert">
		<h4 class="icon-notification">&nbsp;Este auto aún no tiene ordenes de servicio</h4>
	</div>
	{% endif %}
{% endblock content %}

vehiculos/templates/list_vehiculo.html
{% extends "base.html" %}
{% block contentViewTitle %}
	<h3>
		Lista de Vehiculos
		<a href="{% url 'create_vehiculo' %}" class="btn btn-primary">Nuevo Vehiculo</a>
	</h3>
{% endblock contentViewTitle %}
{% block content %}
	{% if messages %}
		<div class="alert alert-success " role="alert">
			{% for message in messages %}
				{{ message }}
			{% endfor %}
		</div>
	{% endif %}
	<table class="table table-striped table-hover" id="table">
		<thead>
			<tr>
				<th>Placa</th>
				<th>Soat</th>
				<th>Cilindraje</th>
				<th>Marca</th>
				<th>Linea</th>
				<th>Cliente</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			{% for vehiculo in vehiculos %}
				<tr>
					<td>{{ vehiculo.placa }}</td>
					{% if vehiculo.soat %}
						<td>{{ vehiculo.soat }}</td>
					{% else %}
						<td></td>
					{% endif %}						
					<td>{{ vehiculo.cilindraje }}</td>
					<td>{{ vehiculo.linea.marca }}</td>
					<td>{{ vehiculo.linea }}</td>
					<td>{{ vehiculo.cliente }}</td>
					<td>
						<a href="{% url 'detail_vehiculo' vehiculo.pk %}" class="btn btn-primary">Ver</a>
						<a href="{% url 'update_vehiculo' vehiculo.pk %}" class="btn btn-primary">Editar</a>
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
	<div class="row">
		{% if is_paginated %}
			{% if page_obj.has_previous %}
				<a class="paginate-change" href="{% url 'list_vehiculo' %}?page={{ page_obj.previous_page_number }}">
					atrás&nbsp;
				</a>
			{% endif %}
			<span class="page-current">
				Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
			</span>
			{% if page_obj.has_next %}
				<a class="paginate-change" href="{% url 'list_vehiculo' %}?page={{ page_obj.next_page_number }}">
					&nbsp;siguiente
				</a>
			{% endif %}
		{% endif %}
	</div>
{% endblock content %}

vehiculos/templates/pdf_vehiculo_soat.html
{% load humanize %}

{% load custom_filters %}

{% load static %}

<html>
	<head>
		<title>{{ title }}</title>
		<style type="text/css">
			@page {
				size: letter portrait;
				@frame header_frame {
					top: 1cm;
					-pdf-frame-content: header_content;
				}
				@frame content_frame{
					top: 4.9cm;
				}
				@frame footer {
					-pdf-frame-content: footerContent;
					bottom: 0cm;
					height: 1cm;
				}
			}
			body {
				text-align: center;
				font-size: 12px;
				font-family: 'Courier Bold';
			}
			img { zoom: 80%; }
			table {
				border-collapse: collapse;
			}
			td, th {
				padding: 1px 0px;
			}
		</style>
	</head>
	<body>
		<table id="header_content">
			<thead>
				<tr>
					<th>TALLER ALMACEN DE REPUESTOS LT MOTORS S.A.S</th>
				</tr>
				<tr>
					<th>CR 10 # 24 - 33 BARRIO SUCRE</th>
				</tr>
				<tr>
					<th>NIT: 900620734-2</th>
				</tr>
				<tr>
					<th>GIRARDOT - CUNDINAMARCA</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>_________________________________________________________________________________________</td>
				</tr>
				<tr>
					<th>
						<h1>LISTADO DE SOAT PRÓXIMO A VENCIMIENTO DE VEHICULOS</h1>
					</th>
				</tr>
			</tbody>
		</table>
		<table width="80%" align="center">
			<thead>
				<tr>
					<th style="text-align: left; width: 90px;">Placa</th>
					<th style="text-align: left; width: 110px;">Cilindraje</th>
					<th style="text-align: left;">Cliente</th>
					<th style="text-align: left;">Fecha Soat</th>
					<th style="text-align: left; width: 70px;">Estado</th>
				</tr>
			</thead>
			<tbody>
				{% for vehiculo in vehiculo_data %}
					<tr>
						<td style="text-align: left;">{{ vehiculo.placa }}</td>
						<td style="text-align: left;">{{ vehiculo.cilindraje }}</td>
						<td style="text-align: left;">{{ vehiculo.cliente }}</td>
						<td style="text-align: left;">{{ vehiculo.soat }}</td>
						<td style="text-align: left;">{% if vehiculo.soat < fecha_hoy %}Vencido{% else %}Al día{% endif %}</td>
					</tr>
					<tr>
						<td colspan="5">------------------------------------------------------------------------------------------------------------------------------------------------------------------------</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</body>
</html>

vehiculos/templates/soat.html
{% extends "base.html" %}
{% block contentViewTitle %}
	<h3>
		Lista de SOAT vencidos
	</h3>
{% endblock contentViewTitle %}
{% block content %}
	<table class="table table-striped table-hover ">
		<thead>
			<tr>
				<th>Placa</th>
				<th>Fecha SOAT</th>
				<th>Cilindraje</th>
				<th>Cliente</th>
				<th>Estado</th>
				<th>Acción</th>
			</tr>
		</thead>
		<tbody>
			{% for soat_data in soat %}
				<tr>
					<td>{{ soat_data.placa }}</td>
					<td>{{ soat_data.soat }}</td>
					<td>{{ soat_data.cilindraje }}</td>
					<td>{{ soat_data.cliente }}</td>
					<td>Vencido</td>
					<td>
						<a href="{% url 'update_vehiculo' soat_data.pk %}" class="btn btn-primary">Editar</a>
					</td>
				</tr>
			{% empty %}
				<h3 class="text-center">No hay SOAT vencidos</h3>
			{% endfor %}
		</tbody>
	</table>
{% endblock content %}

vehiculos/templates/vehiculo_soat.html
{% extends "base.html" %}

{% block contentViewTitle %}
	<h3>Reporte servicios por auto</h3>
{% endblock contentViewTitle %}

{% load staticfiles %}

{% block head %}
	<script src="{% static 'js/moment.js' %}"></script>
	<link rel="stylesheet" href="{% static 'css/bootstrap.datetimepicker.css' %}">
	<script src="{% static 'js/bootstrap.datetimepicker.js' %}"></script>
{% endblock head %}

{% block content %}
	<p>Ingrese los datos solicitados</p>
	<div class="row">
		<form action="" method="POST" class="col-8">
			{% csrf_token %}
			{% for form in forms %}
				<div class="form-group">
					<label>{{ form.label }}</label>
					{{ form }}
				</div>
			{% endfor %}
			<input type="submit" class="btn btn-success" >
		</form>
	</div>
{% endblock content %}

{% block scripts %}
	<script>
		$('.datepicker').datetimepicker({format: 'YYYY-MM-DD'});
		$('form').submit(function(){
			var id_fecha_in = $('#id_fecha_in').val();
			var id_fecha_fin = $('#id_fecha_fin').val();
			if(id_fecha_in > id_fecha_fin){
				alert('La fecha inicial debe ser menor a la fecha inicial');
				$('#id_fecha_in').val('');
				$('#id_fecha_fin').val('');
			}else{
				window.open('/vehivulo-reporte-soat/'+id_fecha_in+'/'+id_fecha_fin+'/', '_blank');
			}
			return false;
		});
	</script>
{% endblock scripts %}