ordenes_servicios/urls.py
from django.conf.urls import include, url
from .views import *

urlpatterns = [
	url(r'^orden-servicio/$', 'ordenes_servicios.views.ordenServicio', name = 'orden_servicio'),
	url(r'^orden-servicio/nueva/(?P<pk>[\w\-]+)/$', 'ordenes_servicios.views.ordenServicioNueva', name = 'create_orden_servicio'),
	url(r'^orden-servicio/editar/(?P<pk>[\w\-]+)/(?P<orden>[\w\-]+)/$', 'ordenes_servicios.views.ordenServicioEditar', name = 'edit_orden_servicio'),
	url(r'^guardar-orden/$', 'ordenes_servicios.views.guardarOrden', name = 'guardar_orden'),
	url(r'^orden-servicio/(?P<pk>[\w\-]+)/$', 'ordenes_servicios.views.detalleOrdenServicio', name = 'detalle_orden_servicio'),
	url(r'^delete-orden-servicio/(?P<pk>[\w\-]+)/$', 'ordenes_servicios.views.delete_orden_servicio', name = 'delete_orden_servicio'),

	#Reportes urls
	url(r'^orden-servicio-auto/$', 'ordenes_servicios.views.orden_servicio_auto', name = 'orden_servicio_auto'),
	url(r'^orden-servicio-mecanico/$', 'ordenes_servicios.views.orden_servicio_mecanico', name = 'orden_servicio_mecanico'),
	url(r'^ordenes-por-servicios/$', 'ordenes_servicios.views.ordenes_por_servicios', name = 'ordenes_por_servicios'),
	#PDF
	url(r'^orden-servicio-reporte-auto/(?P<placa>[\w\-]+)/(?P<fecha_in>[\w\-]+)/(?P<fecha_fin>[\w\-]+)/$', OrdenReporteAutoPDFView.as_view(), name = 'orden_servicio_reporte_auto'),
	url(r'^orden-servicio-reporte-mecanico/(?P<mecanico>[\w\-]+)/(?P<fecha_in>[\w\-]+)/(?P<fecha_fin>[\w\-]+)/$', OrdenReporteMecanicoPDFView.as_view(), name = 'orden_servicio_reporte_mecanico'),
	url(r'^ordenes-por-servicios-reporte/(?P<servicio>[\w\-]+)/(?P<fecha_in>[\w\-]+)/(?P<fecha_fin>[\w\-]+)/$', OrdenesPorServicioReportePDFView.as_view(), name = 'ordenes_por_servicios_reporte'),
	url(r'^orden-servicio/imprimir/(?P<orden_pk>[\w\-]+)/$', OrdenServicioReportePDFView.as_view(), name = 'imprimir_orden_servicio'),

	#Ajax request Urls
	url(r'^getServicioValor/$','ordenes_servicios.views.getServicioValor', name = 'get_servicio_valor'),
	url(r'^mecanicos/tiempos$', 'maestros.views.time_mecanicos', name = 'time_mecanicos'),
	url(r'^mecanicos/disponibilidad/$', 'maestros.views.disp_mecanico', name = 'disp_mecanico'),

]

ordenes_servicios/models.py
from datetime import datetime

from django.db import models

from vehiculos.models import vehiculoModel
from articulos_servicios.models import servicioModel
from maestros.models import mecanicoModel


class ordenServicioModel(models.Model):
	vehiculo = models.ForeignKey(vehiculoModel,null=False,blank=False)
	fecha = models.DateTimeField(null=False,blank=False,default=datetime.now)
	state = models.PositiveIntegerField(default = 1)

	def __str__(self):
		return u'%s' % (self.pk)

	def __unicode__(self):
		return u'%s' % (self.pk)

class ordenServicioDetalleModel(models.Model):
	servicio = models.ForeignKey(servicioModel,null=False,blank=False)
	cantidad = models.PositiveIntegerField(null=True,blank=True)
	valorUnitario = models.PositiveIntegerField(null=True,blank=True,verbose_name='V. Unitario')
	valorTotal = models.PositiveIntegerField(null=True,blank=True, verbose_name='V. Total')
	mecanico = models.ForeignKey(mecanicoModel,null=True,blank=True)
	ordenServicio = models.ForeignKey(ordenServicioModel,null=False,blank=False)
	time = models.TimeField(auto_now = False, null = True, blank = True)
	fecha = models.DateField(null=True,blank=True,auto_now=True)

	def __str__(self):
		return u'%s - %s' % (self.ordenServicio, self.pk)

	def __unicode__(self):
		return u'%s - %s' % (self.ordenServicio, self.pk)

ordenes_servicios/forms.py
from django import forms
from maestros.models import mecanicoModel
from datetime import datetime, time, timedelta
from articulos_servicios.models import servicioModel
from vehiculos.models import vehiculoModel
from ordenes_servicios.models import ordenServicioDetalleModel, ordenServicioModel

class vehiculoOrdenForm(forms.Form):
	placa = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

class ordenServicioAutoForm(forms.Form):
	placa = forms.ChoiceField(label = "Placa del auto", choices = [('','Seleccione un Auto')]+[('ALL', 'Todos')]+[(x.placa, x.placa) for x in vehiculoModel.objects.all()], widget = forms.Select(attrs = {'class': 'form-control', 'required': True}))
	fecha_in = forms.CharField(label = "Fecha de inicio", widget = forms.TextInput(attrs = {'class': 'form-control datepicker', 'required': True}))
	fecha_fin = forms.CharField(label = "Fecha Final", widget = forms.TextInput(attrs = {'class': 'form-control datepicker', 'required': True}))

class ordenServicioMecanicoForm(forms.Form):
	mecanico = forms.ChoiceField(label = "Mecanico", choices = [('','Seleccione un Mecanico')]+[('ALL', 'Todos')]+[(x.pk, x.nombre+' '+x.apellido) for x in mecanicoModel.objects.all()], widget = forms.Select(attrs = {'class': 'form-control', 'required': True}))
	fecha_in = forms.CharField(label = "Fecha de inicio", widget = forms.TextInput(attrs = {'class': 'form-control datepicker', 'required': True}))
	fecha_fin = forms.CharField(label = "Fecha Final", widget = forms.TextInput(attrs = {'class': 'form-control datepicker', 'required': True}))

class ordenPorServicioForm(forms.Form):
	servicio = forms.ChoiceField(label = "Servicios", choices = [('','Seleccione un Servicio')]+[('ALL', 'Todos')]+[(x.pk, x.nombre) for x in servicioModel.objects.all()], widget = forms.Select(attrs = {'class': 'form-control', 'required': True}))
	fecha_in = forms.CharField(label = "Fecha de inicio", widget = forms.TextInput(attrs = {'class': 'form-control datepicker', 'required': True}))
	fecha_fin = forms.CharField(label = "Fecha Final", widget = forms.TextInput(attrs = {'class': 'form-control datepicker', 'required': True}))

class ordenServicioDetalle(forms.ModelForm):
	class Meta:
		model = ordenServicioDetalleModel
		exclude = ['ordenServicio']
		widgets = {
			'valorTotal': forms.NumberInput(attrs={'disabled' : 'disabled'})
		}

	def __init__(self, *args, **kwargs):
		service = kwargs.pop('service', None)
		detail_service = [x.servicio.pk for x in ordenServicioDetalleModel.objects.filter(ordenServicio = service)]
		super(ordenServicioDetalle, self).__init__(*args, **kwargs)
		self.fields['servicio'] = forms.ChoiceField(label = "Servicio", choices = [('','Seleccione un Servicio')]+[(x.pk, x.nombre) for x in servicioModel.objects.exclude(pk__in = detail_service).distinct()], widget = forms.Select(attrs = {'class': 'form-control', 'required': True}))
		self.fields['mecanico'] = forms.ChoiceField(label = "Mecanico", choices = [('','Seleccione un Mecanico')]+[(x.pk, x.nombre) for x in mecanicoModel.objects.all()], widget = forms.Select(attrs = {'class': 'form-control', 'required': True}))

	def save(self):
		ordenServicio = ordenServicioModel.objects.get(pk = str(self.instance))
		servicio = servicioModel.objects.get(pk = self.cleaned_data.get('servicio'))
		mecanico = mecanicoModel.objects.get(pk = self.cleaned_data.get('mecanico'))
		detalle_orden = ordenServicioDetalleModel(servicio = servicio, mecanico = mecanico, time = get_time(servicio.time), ordenServicio = ordenServicio)
		detalle_orden.save()
		return detalle_orden

def get_time(time):
	time_service = datetime.strptime(str(time), '%H:%M:%S')
	time_now = datetime.now()
	time = time_now + timedelta(hours = time_service.hour, minutes = time_service.minute)
	return time

ordenes_servicios/templates/edit_orden_servicio.html
{% extends "base.html" %}
{% load staticfiles %}

{% block contentViewTitle %}
	<h3>
		Orden de servicio
	</h3>
	<div style="position: absolute; right: 100px;">
		{% if orden.state == 1 %}
			<a href="{% url 'tramite_service' orden.pk %}" class="btn btn-info btn-sm" id="close">tramite</a>
		{% endif %}
			<a href="{% url 'close_service' orden.pk %}" class="btn btn-danger btn-sm" id="close">cerrar</a>
	</div>
{% endblock contentViewTitle %}
{% block content %}
	<div class="well orden-servicio">
		<h4>Datos del Vehiculo</h4>
		<div class="row orden-datos-vehiculo">
			<div class="col-md-8">
				<div class="col-md-3">
					<span class="labelfield">Placa</span>
					<span class="dato">{{ vehiculo.placa }}</span>
				</div>
				<div class="col-md-3">
					<span class="labelfield">Marca</span>
					<span class="dato">{{ vehiculo.marca }}</span>
				</div>
				<div class="col-md-3">
					<span class="labelfield">Modelo</span>
					<span class="dato">{{ vehiculo.modelo }}</span>
				</div>
				<div class="col-md-3">
					<span class="labelfield">Linea</span>
					<span class="dato">{{ vehiculo.linea }}</span>
				</div>
				<div class="col-md-3">
					<span class="labelfield">Cilindraje</span>
					<span class="dato">{{ vehiculo.cilindraje }}</span>
				</div>
				<div class="col-md-3">
					<span class="labelfield">Kilometraje</span>
					<span class="dato">{{ vehiculo.kilometraje_actual }}</span>
				</div>
			</div>
			<div class="col-md-4">
				<img src="{% static vehiculo.foto %}" style="width: 300px;" alt="">
			</div>
		</div>
		<div class="separator-horizontal"></div>
		<h4>Datos del Cliente</h4>
		<div class="row orden-datos-cliente">
			<div class="col-3">
				<span class="labelfield">Nombre</span>
				<span class="dato">{{ vehiculo.cliente }}</span>
			</div>
			<div class="col-2">
				<span class="labelfield">Documento</span>
				<span class="dato">{{ vehiculo.cliente.documento }}</span>
			</div>
			<div class="col-3">
				<span class="labelfield">Telefono</span>
				<span class="dato">{{ vehiculo.cliente.celular }} - {{ vehiculo.cliente.telefono }}</span>
			</div>
			<div class="col-3">
				<span class="labelfield">Dirección</span>
				<span class="dato">{{ vehiculo.cliente.direccion }}</span>
			</div>
		</div>
		<div class="row orden-datos-servicio">
			<table class="table table-striped table-hover ">
				<thead>
					<tr>
						<th>Servicio</th>
						<th>Cantidad</th>
						<th>Descripción</th>
						<th>V. Unitario</th>
						<th>Mecánico</th>
						<th>Tiempo</th>
						<th>V. Total</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					{% for detalle in orden.ordenserviciodetallemodel_set.all %}
						<tr id="object-{{ detalle.pk }}">
							<td>{{ detalle.servicio }}</td>
							<td>{{ detalle.cantidad }}</td>
							<td>{{ detalle.servicio.detail }}</td>
							<td>{{ detalle.valorUnitario }}</td>
							<td>{{ detalle.mecanico }}</td>
							<td>{{ detalle.servicio.time }} Hrs</td>
							<td>{{ detalle.valorTotal }}</td>
							<td>
								<a href="{% url 'delete_orden_servicio' detalle.pk %}" class="btn btn-danger delete" id="{{ detalle.pk }}">
									<i class="glyphicon glyphicon-remove"></i>
								</a>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		<div class="separator-horizontal"></div>
		<form id="form-servicio" method="POST">
			<div class="row orden-datos-servicio">
				<div class="col-2 center">
					{{ formDetalleOrden.servicio.label_tag }}
					<span class="labelfield">{{ formDetalleOrden.servicio }}</span>
				</div>
				<div class="col-1 center">
					{{ formDetalleOrden.cantidad.label_tag }}
					{{ formDetalleOrden.cantidad }}
				</div>
				<div class="col-2 center">
					<label>Detalle</label>
					<input type="text" name="detalle" id="detalle" readonly>
				</div>
				<div class="col-2 center">
					{{ formDetalleOrden.valorUnitario.label_tag }}
					{{ formDetalleOrden.valorUnitario }}
				</div>
				<div class="col-1 center">
					{{ formDetalleOrden.valorTotal.label_tag }}
					{{ formDetalleOrden.valorTotal }}
				</div>
				<div class="col-2 center">
					{{ formDetalleOrden.mecanico.label_tag }}
					{{ formDetalleOrden.mecanico }}
				</div>
				<div class="col-2 bottom text-center flex">
					<input class="btn btn-success all-space" value="Agregar" type="submit">
				</div>
			</div>
		</form>
		<form id="form-save" action="{% url 'guardar_orden' %}?orden={{ orden.pk }}" method="POST">
				<input type="hidden" id="placa" name="placa" value="{{ vehiculo.placa }}">
			<div id="orden-items">
			</div>
			<div class="separator-horizontal"></div>
			<div class="row end">
				<input id="form-save-btn" type="submit" class="btn btn-success mright-15" value="Guardar" disabled>
				<a href="{% url 'home' %}" class="btn btn-danger">Cancelar</a>
		</form>
		</div>
	</div>
{% endblock content %}
{% block scripts %}
	<script src="{% static "js/jquery.min.js" %}"></script>
	<script>
		$(document).on("click", ".delete", function(){
			var id = $(this).attr('id');
			var href = $(this).attr('href');
			$.get(href, function(data){
				$('#object-'+id).remove();
			});
			return false;
		});
		var form = document.getElementById('form-servicio')
		var servicio = document.getElementById('id_servicio')
		var valor = document.getElementById('id_valorUnitario')
		var cantidad = document.getElementById('id_cantidad')
		var vTotal = document.getElementById('id_valorTotal')

		servicio.addEventListener('change', function(){
			if( this.value )
				getServicioData(this.value)
		})
		valor.addEventListener('change', function(){
			valorTotal()
		})
		cantidad.addEventListener('change', function(){
			valorTotal()
		})
		form.onsubmit = function(e){
			e.preventDefault()
			var check = checkFormServicio(form)
			if (!check)
				alert("Llene todos los campos")
			else
				addServicio(form)
		}

		function addServicio (form) {
			var html = "<div class='row orden-servicio-item'><div class='col-3 center'><input id=''  type='text' disabled value='"+form.servicio.options[form.servicio.selectedIndex].text+"'> <input type='hidden' id='servicio' name='servicios[]' value='"+form.servicio.options[form.servicio.selectedIndex].value+"'/></div><div class='col-1 center'><input id='' type='number' disabled value='"+form.elements.id_cantidad.value+"'><input id='cantidad' name='cantidades[]' type='hidden' value='"+form.elements.id_cantidad.value+"'></div><div class='col-2 center'><input id='vunitario' name='vunitarios[]' type='number' disabled value="+form.elements.id_valorUnitario.value+"></div><div class='col-2 center'><input id='vtotal' name='vtotales[]' type='number' disabled value='"+form.elements.id_valorTotal.value+"'></div><div class='col-2 center'><input id='' type='text' disabled value='"+form.mecanico.options[form.mecanico.selectedIndex].text+"'><input type='hidden' id='mecanico' name='mecanicos[]' value='"+form.mecanico.options[form.mecanico.selectedIndex].value+"'/></div></div>";

			$('#orden-items').append(html);
			var btn = document.getElementById('form-save-btn')
			btn.disabled = false
			form.reset()
		}

		function checkFormServicio (form) {
			var elements = form.elements
			for (var i = 0; i < elements.length; i++) {
				if(!elements[i].value)
					return false
			}
			return true
		}
		function valorTotal(){
			vTotal.value = valor.value * cantidad.value
		}
		function getServicioData(servicio){
			//get data from JSON
			// {valor}

			$.ajax({
				method: "GET",
				url:'{% url 'get_servicio_valor' %}',
				data: { servicio: servicio }
			})
			.done(function( json ) {
				valor.value = json.valor
				$('#detalle').val(json.detalle)
				cantidad.value = 1
				valorTotal()
			});

		}

	</script>
{% endblock scripts %}

ordenes_servicios/templates/orden_servicio_auto.html
{% extends "base.html" %}

{% block contentViewTitle %}
	<h3>Reporte servicios por auto</h3>
{% endblock contentViewTitle %}

{% load staticfiles %}

{% block head %}
	<script src="{% static 'js/moment.js' %}"></script>
	<link rel="stylesheet" href="{% static 'css/bootstrap.datetimepicker.css' %}">
	<script src="{% static 'js/bootstrap.datetimepicker.js' %}"></script>
{% endblock head %}

{% block content %}
	<p>Ingrese los datos solicitados</p>
	<div class="row">
		<form action="" method="POST" class="col-8">
			{% csrf_token %}
			{% for form in forms %}
				<div class="form-group">
					<label>{{ form.label }}</label>
					{{ form }}
				</div>
			{% endfor %}
			<input type="submit" class="btn btn-success" >
		</form>
	</div>
{% endblock content %}

{% block scripts %}
	<script>
		$('.datepicker').datetimepicker({format: 'YYYY-MM-DD'});
		$('form').submit(function(){
			var id_fecha_in = $('#id_fecha_in').val();
			var id_fecha_fin = $('#id_fecha_fin').val();
			var placa = $('#id_placa').val();
			if(id_fecha_in > id_fecha_fin){
				alert('La fecha inicial debe ser menor a la fecha inicial');
				$('#id_fecha_in').val('');
				$('#id_fecha_fin').val('');
			}else{
				window.open('/orden-servicio-reporte-auto/'+placa+'/'+id_fecha_in+'/'+id_fecha_fin+'/', '_blank');
			}
			return false;
		});
	</script>
{% endblock scripts %}

ordenes_servicios/templates/orden_servicio_mecanico.html
{% extends "base.html" %}

{% block contentViewTitle %}
	<h3>Reporte servicios por mecanico</h3>
{% endblock contentViewTitle %}

{% load staticfiles %}

{% block head %}
	<script src="{% static 'js/moment.js' %}"></script>
	<link rel="stylesheet" href="{% static 'css/bootstrap.datetimepicker.css' %}">
	<script src="{% static 'js/bootstrap.datetimepicker.js' %}"></script>
{% endblock head %}

{% block content %}
	<p>Ingrese los datos solicitados</p>
	<div class="row">
		<form action="" method="POST" class="col-8">
			{% csrf_token %}
			{% for form in forms %}
				<div class="form-group">
					<label>{{ form.label }}</label>
					{{ form }}
				</div>
			{% endfor %}
			<input type="submit" class="btn btn-success" >
		</form>
	</div>
{% endblock content %}

{% block scripts %}
	<script>
		$('.datepicker').datetimepicker({format: 'YYYY-MM-DD'});
		$('form').submit(function(){
			var id_fecha_in = $('#id_fecha_in').val();
			var id_fecha_fin = $('#id_fecha_fin').val();
			var mecanico = $('#id_mecanico').val();
			if(id_fecha_in > id_fecha_fin){
				alert('La fecha inicial debe ser menor a la fecha inicial');
				$('#id_fecha_in').val('');
				$('#id_fecha_fin').val('');
			}else{
				window.open('/orden-servicio-reporte-mecanico/'+mecanico+'/'+id_fecha_in+'/'+id_fecha_fin+'/', '_blank');
			}
			return false;
		});
	</script>
{% endblock scripts %}

ordenes_servicios/templates/pdf_orden_reporte_auto.html
{% load humanize %}

{% load custom_filters %}

{% load static %}

<html>
	<head>
		<title>{{ title }}</title>
		<style type="text/css">
			@page {
				size: letter portrait;
				@frame header_frame {
					top: 1cm;
					-pdf-frame-content: header_content;
				}
				@frame content_frame{
					top: 4.9cm;
				}
				@frame footer {
					-pdf-frame-content: footerContent;
					bottom: 0cm;
					height: 1cm;
				}
			}
			body {
				text-align: center;
				font-size: 12px;
				font-family: 'century gothic';
			}
			img { zoom: 80%; }
			table {
				border-collapse: collapse;
			}
			td, th {
				padding: 1px 0px;
			}
		</style>
	</head>
	<body>
		<table id="header_content">
			<thead>
				<tr>
					<th>TALLER ALMACEN DE REPUESTOS LT MOTORS S.A.S</th>
				</tr>
				<tr>
					<th>CR 10 # 24 - 33 BARRIO SUCRE</th>
				</tr>
				<tr>
					<th>NIT: 900620734-2</th>
				</tr>
				<tr>
					<th>GIRARDOT - CUNDINAMARCA</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>_________________________________________________________________________________________</td>
				</tr>
				<tr>
					<th>
						<h1>HISTORIAL DE SERVICIOS POR AUTO</h1>
					</th>
				</tr>
			</tbody>
		</table>
		{% regroup orden_servicio by vehiculo as orden_servicio_list %}
		{% for orden in orden_servicio_list %}
			<table width="70%" align="center">
				<tbody style="text-align: left">
					<tr>
						<th>Placa:</th>
						<td>{{ orden.grouper.placa }}</td>
						<th>Nombre:</th>
						<td>{{ orden.grouper.cliente.nombre }}</td>
					</tr>
					<tr>
						<th>Cilindraje:</th>
						<td>{{ orden.grouper.cilindraje }}</td>
						<th>Cédula:</th>
						<td>{{ orden.grouper.cliente.documento }}</td>
					</tr>
					<tr>
						<th>Marca:</th>
						<td>{{ orden.grouper.marca }}</td>
						<th>Telefono:</th>
						<td>{{ orden.grouper.cliente.telefono }}</td>
					</tr>
					<tr>
						<th></th>
						<td></td>
						<th>Email:</th>
						<td>{{ orden.grouper.cliente.email }}</td>
					</tr>
				</tbody>
			</table>
			<table width="90%" align="center">
				<thead>
					<tr>
						<th>Fecha</th>
						<th>Servicio</th>
						<th>Descripcion</th>
						<th>Mecanico</th>
					</tr>
				</thead>
				<tbody>
					{% for item in orden.list %}
						{% for item_detail in item.ordenserviciodetallemodel_set.all %}
							<tr>
								<td>{{ item.fecha }}</td>
								<td>{{ item_detail.servicio.nombre }}</td>
								<td>{{ item_detail.servicio.detail }}</td>
								<td>{{ item_detail.mecanico.nombre }}</td>
							</tr>
						{% endfor %}
					{% endfor %}
				</tbody>
			</table>
			-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
		{% endfor %}
	</body>
</html>

ordenes_servicios/templates/pdf_orden_servicio_reporte.html
{% load humanize %}

{% load static %}

<html>
	<head>
		<title>{{ title }}</title>
		<style type="text/css">
			@page {
				size: letter portrait;
				@frame header_frame {
					top: 1cm;
					-pdf-frame-content: header_content;
				}
				@frame content_frame{
					top: 4cm;
				}
				@frame footer {
					-pdf-frame-content: footerContent;
					bottom: 0cm;
					height: 1cm;
				}
			}
			body {
				text-align: center;
				font-size: 12px;
				font-family: 'century gothic';
			}
			table {
				border-collapse: collapse;
			}
			td, th {
				padding: 1px 0px;
			}
		</style>
	</head>
	<body>
		<table id="header_content">
			<thead>
				<tr>
					<th>TALLER ALMACEN DE REPUESTOS LT MOTORS S.A.S</th>
				</tr>
				<tr>
					<th>CR 10 # 24 - 33 BARRIO SUCRE</th>
				</tr>
				<tr>
					<th>NIT: 900620734-2</th>
				</tr>
				<tr>
					<th>GIRARDOT - CUNDINAMARCA</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>_________________________________________________________________________________________</td>
				</tr>
			</tbody>
		</table>
		<table width="80%" align="center">
			<thead>
				<tr>
					<td><b>Fecha:</b> {{ servicio_data.fecha }}</td>
					<td><b>No. Orden:</b> {{ servicio_data.pk }}</td>
				</tr>
			</thead>
		</table>
		<table width="80%" align="center" style="background-color: #F5F5F5; margin-bottom: 15px;">
			<thead>
				<tr>
					<th colspan="4" style="text-align: left; padding: 5px;">
						DATOS DEL SERVICIO
					</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<th>Placa</th>
					<th>Marca</th>
					<th>Modelo</th>
					<th>Línea</th>
				</tr>
				<tr>
					<td>{{ servicio_data.vehiculo }}</td>
					<td>{{ servicio_data.vehiculo.linea.marca }}</td>
					<td>{{ servicio_data.vehiculo.modelo }}</td>
					<td>{{ servicio_data.vehiculo.linea }}</td>
				</tr>
				<tr>
					<th>Cilindraje</th>
					<th>Kilometraje</th>
					<th>SOAT</th>
				</tr>
				<tr>
					<td>{{ servicio_data.vehiculo.cilindraje }}</td>
					<td>{{ servicio_data.vehiculo.kilometraje_actual }}</td>
					<td>{{ servicio_data.vehiculo.soat }}</td>
				</tr>
			</tbody>
		</table>
		<table width="80%" align="center" style="background-color: #F5F5F5; margin-bottom: 25px;">
			<thead>
				<tr>
					<th colspan="4" style="text-align: left; padding: 5px;">
						DATOS DEL CLIENTE
					</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<th>Nombre</th>
					<th>Documento</th>
					<th>Teléfono</th>
					<th>Dirección</th>
				</tr>
				<tr>
					<td>{{ servicio_data.vehiculo.cliente }}</td>
					<td>{{ servicio_data.vehiculo.cliente.documento }}</td>
					<td>{{ servicio_data.vehiculo.cliente.celular }} - {{ servicio_data.vehiculo.cliente.telefono }}</td>
					<td>{{ servicio_data.vehiculo.cliente.direccion }}</td>
				</tr>
			</tbody>
		</table>
		<table width="90%" align="center">
			<thead>
				<tr>
					<th>Servicio</th>
					<th>Cantidad</th>
					<th>Descripción</th>
					<th>V. Unitario</th>
					<th>Mecánico</th>
					<th>Tiempo</th>
					<th>V. Total</th>
				</tr>
			</thead>
			<tbody>
				{% for detalle in servicio_data.ordenserviciodetallemodel_set.all %}
					<tr>
						<td>{{ detalle.servicio }}</td>
						<td>{{ detalle.cantidad }}</td>
						<td>{{ detalle.servicio.detail }}</td>
						<td>{{ detalle.valorUnitario }}</td>
						<td>{{ detalle.mecanico }}</td>
						<td>{{ detalle.servicio.time }} Hrs</td>
						<td>{{ detalle.valorTotal }}</td>
					</tr>
					<tr>
						<td colspan="7" style="color: #999999;">---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</td>
					</tr>
				{% endfor %}
			</tbody>
			<tfoot>
				<tr>
					<th colspan="6">Valor Total</th>
					<th>$ {{ total_valor.valorTotal__sum }}</th>
				</tr>
			</tfoot>
		</table>
	</body>
</html>