articulos_servicios/urls.py
from django.conf.urls import include, url
from articulos_servicios.views import *

urlpatterns = [
	url(r'^servicios/nuevo$', createServicioView.as_view(), name = 'create_servicio'),
	url(r'^servicios/$', listServicioView.as_view(), name = 'list_servicio'),
	url(r'^servicios/actualizar/(?P<pk>\d+)/$', updateServicioView.as_view(), name = 'update_servicios')
]

articulos_servicios/models.py
from django.db import models

class grupoServicioModel(models.Model):
	nombre = models.CharField(max_length=50)

	def __str__(self):
		return u'%s' % (self.nombre)

	def __unicode__(self):
		return u'%s' % (self.nombre)

class servicioModel(models.Model):
	servicio = models.BooleanField(default = True)
	repuesto = models.BooleanField(default = False)
	nombre = models.CharField(max_length=100)
	referencia = models.CharField(max_length = 15, blank = True, null = True)
	valor =  models.PositiveIntegerField()
	grupo = models.ForeignKey(grupoServicioModel, blank = True, null = True)
	time = models.TimeField(default = '0:00:00', blank = True, null = True)
	detail = models.CharField(max_length = 1000, default = '-')
	fecha_vencimiento = models.DateField(blank = True, null = True)

	def __str__(self):
		return u'%s' % (self.nombre)

	def __unicode__(self):
		return u'%s' % (self.nombre)

articulos_servicios/forms.py
from django import forms

from articulos_servicios.models import servicioModel

class servicioModelForm(forms.ModelForm):
	class Meta:
		model = servicioModel
		fields = '__all__'
		widgets = {
			'nombre': forms.TextInput(attrs={'class': 'form-control'}),
			'valor': forms.NumberInput(attrs={'class': 'form-control', 'value': 0, 'min': 0}),
			'time': forms.TextInput(attrs={'class': 'form-control servicio'}),
			'grupo': forms.Select(attrs={'class': 'form-control servicio'}),
			'detail': forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}),
			'fecha_vencimiento': forms.TextInput(attrs={'type': 'date', 'class': 'form-control articulo'}),
			'referencia': forms.TextInput(attrs={'class': 'form-control articulo'}),
		}
		labels = {
			'time': 'Tiempo',
			'detail': 'Detalle',
			'fecha_vencimiento': 'Fecha de vencimiento'
		}

articulos_servicios/views.py
# -*- encoding: utf-8 -*-
from django.shortcuts import render
from django.views.generic import CreateView, ListView, UpdateView
from articulos_servicios.forms import servicioModelForm
from articulos_servicios.models import servicioModel
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import user_passes_test

class createServicioView(CreateView):
	template_name = 'create_servicio.html'
	form_class = servicioModelForm
	success_url = '/servicios/nuevo'

	@method_decorator(user_passes_test(lambda u: u.usuariosmodel.tipoUsuario.nombre_tipo == 'Administrador', login_url='/'))
	def dispatch(self, *args, **kwargs):
		return super(createServicioView,  self).dispatch(*args, **kwargs)

class updateServicioView(UpdateView):
	model = servicioModel
	form_class = servicioModelForm
	template_name = 'create_servicio.html'
	success_url = '/servicios'

	@method_decorator(user_passes_test(lambda u: u.usuariosmodel.tipoUsuario.nombre_tipo == 'Administrador', login_url='/'))
	def dispatch(self, *args, **kwargs):
		return super(updateServicioView,  self).dispatch(*args, **kwargs)

class listServicioView(ListView):
	template_name = 'list_servicio.html'
	model = servicioModel
	context_object_name = 'servicios'

	@method_decorator(user_passes_test(lambda u: u.usuariosmodel.tipoUsuario.nombre_tipo == 'Administrador', login_url='/'))
	def dispatch(self, *args, **kwargs):
		return super(listServicioView,  self).dispatch(*args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super(listServicioView, self).get_context_data(**kwargs)
		seresp = servicioModel.objects.all()
		context['servicios_data'] = seresp.filter(servicio = True)
		context['repuestos_data'] = seresp.filter(repuesto = True)
		return context

articulos_servicios/templates/create_servicio.html
{% extends "base.html" %}
{% block contentViewTitle %}
	<h3>Crear nuevo <b class="title"></b></h3>
{% endblock contentViewTitle %}
{% block content %}
	{% if form.errors %}
		<div class="alert alert-danger">
			Corrija los <strong>errores</strong> por favor
			<p>{{ form.non_field_errors }}</p>
		</div>
	{% endif %}
	<div class="well">
		<form method="POST">
			{% csrf_token %}
			{% for forms in form %}
				<div class="form-group">
					{{ forms.errors }}
					<label>{{forms.label}}</label>
					{{ forms }}
				</div>
			{% endfor %}
			<input type="submit" class="btn btn-success" value="Crear">
		</form>
	</div>
{% endblock content %}

{% block scripts %}
	<script>
		verify_checked();
		function verify_checked(){
			if($('input#id_servicio').is(':checked')){
				$('.articulo').hide()
				$('.articulo').prev().hide()
				$('.servicio').show()
				$('.servicio').prev().show()
				$('.title').empty().text('Servicio')
			}
			if($('input#id_repuesto').is(':checked')){
				$('.articulo').show()
				$('.articulo').prev().show()
				$('.servicio').hide()
				$('.servicio').prev().hide()
				$('.title').empty().text('Articulo')
			}
		}
		$('#id_servicio').click(function(){
			$("input#id_repuesto").prop( "checked", false)
			verify_checked();
		});
		$('#id_repuesto').click(function(){
			$("input#id_servicio").prop( "checked", false)
			verify_checked();
		});
	</script>
{% endblock scripts %}

articulos_servicios/templates/list_servicio.html
{% extends "base.html" %}
{% load humanize %}
{% block contentViewTitle %}
	<h3>
		Lista de <span id="titulo"></span>
		<a href="#" class="btn btn-info" id="servicio_btn">Servicios</a>
		<a href="#" class="btn btn-primary" disabled id="repuesto_btn">Repuestos</a>
	</h3>
{% endblock contentViewTitle %}

{% block scripts %}
	<script>
		repuesto();
		function repuesto(){
			$('#repuesto').show();
			$('#servicio').hide();
			$('#titulo').text('Repuestos');
			$('#table-repuesto').DataTable({"language": languageDataTable,});
			$('#table-servicio').DataTable().destroy();
		}
		function servicio(){
			$('#servicio').show();
			$('#repuesto').hide();
			$('#titulo').text('Servicios');
			$('#table-repuesto').DataTable().destroy();
			$('#table-servicio').DataTable({"language": languageDataTable,});
		}
		$('#servicio_btn').click(function(){
			$('#servicio_btn').attr('disabled');
			$('#repuesto_btn').removeAttr('disabled');
			servicio();
		});
		$('#repuesto_btn').click(function(){
			$('#repuesto_btn').attr('disabled');
			$('#servicio_btn').removeAttr('disabled');
			repuesto();
		});
	</script>
{% endblock scripts %}

{% block content %}
	{% if messages %}
		<div class="alert alert-success " role="alert">
			{% for message in messages %}
				{{ message }}
			{% endfor %}
		</div>
	{% endif %}
	<div id="servicio">
		<table class="table table-striped table-hover" id="table-servicio">
			<thead>
				<tr>
					<th>Nombre</th>
					<th>valor</th>
					<th>Tiempo</th>
					<th>Grupo</th>
					<th>Detalle</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				{% for servicio in servicios_data %}
					<tr>
						<td>{{ servicio.nombre }}</td>
						<td>{{ servicio.valor }}</td>
						<td>{{ servicio.time }}</td>
						<td>{{ servicio.grupo }}</td>
						<td>{{ servicio.detail }}</td>
						<td>
							<a href="{% url 'update_servicios' servicio.pk %}" class="btn btn-primary">Editar</a>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
	<div id="repuesto">
		<table class="table table-striped table-hover" id="table-repuesto">
			<thead>
				<tr>
					<th>Nombre</th>
					<th>valor</th>
					<th>Fecha vencimiento</th>
					<th>refencia</th>
					<th>Detalle</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				{% for repuesto in repuestos_data %}
					<tr>
						<td>{{ repuesto.nombre }}</td>
						<td>{{ repuesto.valor }}</td>
						<td>{{ repuesto.fecha_vencimiento }}</td>
						<td>{{ repuesto.referencia }}</td>
						<td>{{ repuesto.detail }}</td>
						<td>
							<a href="{% url 'update_servicios' repuesto.pk %}" class="btn btn-primary">Editar</a>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
	<div class="row center">
		<a class="btn btn-primary" href="{% url 'create_servicio' %}">Nuevo Servicio</a>
	</div>
{% endblock content %}